// post & get

import { prisma } from "@/lib/prisma";
import { NextResponse, NextRequest } from "next/server";

// post: create new task
export async function POST(request: NextRequest){
    try {
        const body = await request.json();
        const {title, description} = body;

        // validate
        // make sure title is not empty
        if (!title || title.trim()===""){
            return NextResponse.json(
                {message: "Title is required."},
                {status: 400}
            );
        }

        // if title is valid, create new task
        const newTask = await prisma.task.create({
            data: {
                // other fields: id, createdAt, updatedAt, deletedAt will be auto generated by prisma
                title: title.trim(),
                description: description?.trim() || null
            }
        });
        return NextResponse.json(
            newTask,
            {status: 201}
        );
        } catch (error) {
            console.error("Error creating task:", error);
            return NextResponse.json(
            { error: "Failed to create task" },
            { status: 500 }
            );
        }
    
}

// get: fetch all tasks
export async function GET(request: NextRequest){
    // wrap in try-catch block to handle errors
    try {
        ///api/tasks?status=completed&sortBy=createdAt
        const searchParams = request.nextUrl.searchParams;
        const status = searchParams.get("status");
        const sortBy = searchParams.get("sortBy") || "createdAt";

        // filtering conditions based on query params
        const where: any = {
            deletedAt: null, // Only get non-deleted tasks
        };

        if (status === "completed") {
            where.completed = true;
        } else if (status === "pending") {
            where.completed = false;
        }


        // fetch tasks from db 
        const tasks = await prisma.task.findMany({
            where, 
            orderBy: {
                [sortBy] : "desc"
            }
        })
        return NextResponse.json(tasks, {status: 200});
    } catch (error) {
    console.error("Error fetching tasks:", error);
    return NextResponse.json(
      { error: "Failed to fetch tasks" },
      { status: 500 }
    );
  }
}